# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  module-test:
    uses: ./.github/workflows/module-test.yml
    permissions:
      id-token: write
      contents: read
    
  security-scan:
    uses: ./.github/workflows/security-scan.yml
    permissions:
      security-events: write
      contents: read
    
  docs-check:
    uses: ./.github/workflows/docs-check.yml
    permissions:
      contents: read