# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  module-test:
    uses: ./.github/workflows/module-test.yml
  security-scan:
    uses: ./.github/workflows/security-scan.yml
  docs-check:
    uses: ./.github/workflows/docs-check.yml