name: Test Modules

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: ['1.5.0', '1.6.0']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}
      
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
      
      - name: Terraform Init
        run: terraform init
        working-directory: modules/${{ matrix.module }}/examples/basic
      
      - name: Terraform Validate
        run: terraform validate
        working-directory: modules/${{ matrix.module }}/examples/basic
      
      - name: Terraform Plan
        run: terraform plan
        working-directory: modules/${{ matrix.module }}/examples/basic